# This rule is not used by the project locust-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the locust.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: locust-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: locusttest-editor-role
rules:
- apiGroups:
  - locust.io
  resources:
  - locusttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - locust.io
  resources:
  - locusttests/status
  verbs:
  - get
