name: ğŸ§ª Go Tests

on:
  push:
    branches: [main, master]
    paths:
      - 'locust-k8s-operator-go/**'
  pull_request:
    paths:
      - 'locust-k8s-operator-go/**'

defaults:
  run:
    working-directory: locust-k8s-operator-go

jobs:
  test:
    name: ğŸ§ Run on Ubuntu
    runs-on: ubuntu-slim
    steps:
      - name: ğŸ“¥ Clone the code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: locust-k8s-operator-go/go.mod

      - name: âœ… Running Tests
        run: |
          go mod tidy
          make test
